clc, clearvars
%10000 trajectories. histogram to see see distribution of lengths. look at
%speed. accuracy of wire in field. make
%sure inside points are different in the eField for the modified and
%unmodified points. (in a different figure). write a report and share it
%online. graphical interface to select points. ranges = user defined percentages.  

% Select fixed points to define wire trajectory
% define these points to correspond within the simulated electric field.

points = [0 -0.05 0 0.0633 0.2 0.25;...
    0 -0.08 0 0.03 -0.3 -0.3;...
     -0.1 0.27 0.35 .58 1 1.4]; 

% Set random range in each direction
x = [0 0;...
    0 -0.08;...
    0 0;...
    0 0;...
    0 0;...
    0 0]; 

y = [-0.01 0.01;...
    -0.05 0.05;...
    -0.07 0;...
    0 0;...
    0 0;...
    0 0];

z = [-0.2 -0.1;...
     -0.15 -0.05;...
     0.29 0;...
     0 0.1;...
     0 0;...
     0.15 0.2];

ranges = [x, y, z];

% Select wire points to randomly move
changing = [1 2 3];

%importfile('Duke 1p5T B1 02Nov21.mat')
s1 = load('simulatedBodyCoilEfield (1).mat');

% [Efield,Axis0,Axis1,Axis2] = interpfield(s1);



%rename sar_short
tic
[arc, modified, values] = wire_function_v5(...
    points',...
    ranges,...
    changing,...
    s1,...
    'nom_length', 1.8,...
    'show_plot', true,...
    'show_graph', true,...
    'intersecting_index', 4,...
    'num_steps', 10,...
    'give_warnings', false);
toc

values;


%Elapsed times:
% 125 trajectories: ~153 seconds
% 1000 trajectories: 924.4 seconds
% 1000000 trajectories: way too long